---
- name: Prepare
  hosts: all
  become: true
  vars:
    ansible_python_interpreter: /usr/bin/python3
    pip_install_packages:
      - name: docker
        executable: pip3
  roles:
    - calvinbui.ansible_pip
